title: Knife Fight Mid
description: "Knife Fight Mid"
owner_name: Zhengji Li, Evan Svetina
github_username: xinjiav3
github_repo: "Knife-Fight-Mid" 
baseurl: "/Knife-Fight-Mid"
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/nighthawkcoders"}
    - { platform: x, user_url: "https://x.com/NighthawkCoding/" }
    - { platform: youtube, user_url: "https://www.youtube.com/@nighthawkcodingsociety2868" } 

# remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme
header_pages:
  - navigation/game.html